services:
  postgres:
    image: postgres:15
    container_name: ferretdb-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ferretdb-data:/var/lib/postgresql/data
    networks:
      - ferretdb-net
    ports:
      - "5432:5432"

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb-eval:2
    container_name: ferretdb
    restart: always
    depends_on:
      - postgres
    environment:
      # Connect to the "postgres" service on port 5432,
      # using "postgres" user, "postgres" password, and DB "ferretdb".
      FERRETDB_POSTGRESQL_URL: "postgres://postgres:postgres@postgres:5432/ferretdb?pool_max_conns=4"
    networks:
      - ferretdb-net
    ports:
      - "27017:27017"

volumes:
  ferretdb-data:

networks:
  ferretdb-net:
